config/routes.rb
Vizbu::Application.routes.draw do
  root :to => "home#index"

  get "search", :to => "home#search"  
  get "about", :to => "home#about"
  get "privacy", :to => "home#privacy"
  get "feedback", :to => "feedbacks#new", :as => :feedback
  
  get "comments", :to => "home#comments", :as => :comments
  
  resources :feedbacks

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def search

    @filters = {
      :youtube => {
        :sort_by => {
          :relevence => {
            :order_by => :relevance
          },
          :view_count => {
            :order_by => :viewCount
          },
          :upload_date => {
            :order_by => :published
          },
          :rating => {
            :order_by => :rating
          }
        },
        :upload_date => {
          :anytime => {
            
          },
          :today => {
            :time => :today
          },
          :this_week => {
            :time => :this_week
          },
          :this_month => {
            :time => :this_month
          }
        },
        :categories => {
          :all => {
            :order_by => :relevance
          },
          :music => {
            :order_by => :viewCount
          },
          :entertainment => {
            :order_by => :published
          }
        },
        :duration => {
          :all => {
            :duration => :relevance
          },
          :short => {
            :duration => :short
          },
          :long => {
            :duration => :long
          }
        },
        :features => {
          :all => {},
          :closed_captions => {
            :caption => true
          },
          :HD => {
            :hd => true
          },
          :partner_videos => {
            :uploader => :partner
          },
          :rental => {
            :paid_content => true
          }
        }
      },
      :vimeo => {
        :sort_by => {
          :relevant => {},
          :newest => {
            :sort => :newest
          },
          :oldest => {
            :sort => :oldest
          },
          :most_played => {
            :sort => :most_played
          },
          :most_commented => {
            :sort => :most_commented
          },
          :most_liked => {
            :sort => :most_liked
          }
        }
      },
      :soundcloud => {
        :sort_by => {
          :hotness => {
            
          },
          :upload_date => {
            :order => :created_at
          }
        },
        :duration => {
          :all => {
            
          },
          :small => {
            "duration[to]" => 1000 * 60 * 4
          },
          :medium => {
            "duration[from]" => 1000 * 60 * 4,
            "duration[to]" => 1000 * 60 * 8
          },
          :long => {
            "duration[from]" => 1000 * 60 * 8
          }
        }
      },
      :dailymotion => {
      },
      :metacafe => {
      }
    }

    @q = params[:q]
    
    if @q.blank?
      redirect_to root_path
      return
    end

    @page = params[:page] || 1

    @source = params[:source] || "youtube"

    @source = @source.to_sym

    @view = params[:view] || "list"

    filter_params = {}
    @filters[@source.to_sym].each do |k, v|
      if !params[k].blank? && !v[params[k].to_sym].blank?
        filter_params.merge!( v[params[k].to_sym] )
      end
    end

    if @source == :youtube
      client = YouTubeIt::Client.new(:dev_key => "AI39si5-1s6CVSSGdBqlMnzN9v_OMBufAMEW-0H4Ke1UG5laQpDCWyWJU5WJlpVHPXSTHyBDHEoFsbBdLfwgHBs7Aic3tjHR0Q")
      @result = client.videos_by({ :query => @q, :page => params[:page] || 1, :per_page => 10 }.merge( filter_params ))
    elsif @source == :vimeo
      video = Vimeo::Advanced::Video.new("0ded35edb12d54c74dbe3622352ceec3", "d07ca9c1a42c7a7")
      @result = video.search(@q, { :page => params[:page] || 1, :per_page => "10", :full_response => "1", :sort => "relevant", :user_id => nil }.merge( filter_params ))
    elsif @source == :soundcloud
      client = Soundcloud.new(:client_id => '718f0504b536fb5b177cfaa4d3cfe847')
      @result = client.get('/tracks', { :offset => @page.to_i * 10, :limit => 10, :order => 'hotness', :q => @q }.merge( filter_params ) )
    elsif @source == :dailymotion
      @result = Dailymotion.get("https://api.dailymotion.com/videos", :query => { :fields => [ :id, :embed_url, :url, :title, :owner, :"owner.username", :"owner.url", :allow_embed, :created_time, :views_total, :duration, :description ], :search => @q, :page => @page, :limit => 10 } )
    elsif @source == :metacafe
      xml_resp = Metacafe.get("http://www.metacafe.com/api/videos/", :query => { :vq => @q, :"start-index" =>  (@page.to_i - 1) * 10, :"max-results" => 10 } )
      @result = Nokogiri::XML(xml_resp)
    end
    
    @orig_result = @result

    @result = normalize_result(@result, @source)

    respond_to do |format|
      format.html {
        if request.headers['X-PJAX']
          render :layout => false #add this option to save the time of layout rendering
        end
      }
      format.js
    end

    #if request.xhr?
    #  render :partial => "full_result", :layout => nil
    #end
  end

  def search_yt

    # don't know how to do category based filtering probably need to use categories retuned in results
    @filters.delete(:categories)

    @q = params[:q]
    client = YouTubeIt::Client.new(:dev_key => "AI39si5-1s6CVSSGdBqlMnzN9v_OMBufAMEW-0H4Ke1UG5laQpDCWyWJU5WJlpVHPXSTHyBDHEoFsbBdLfwgHBs7Aic3tjHR0Q")
    filter_params = {}
    @filters.each do |k, v|
      unless params[k].blank?
        filter_params.merge!( v[params[k].to_sym] )
      end
    end
    @result = client.videos_by({ :query => @q, :page => @page, :per_page => 10 }.merge( filter_params ))
    @view = params[:view] || "list"
  end

  def about
  end
  
  def feedback
  end
  
  def send_feedback
    # send email
    @feedback = Feedback.new(params)
    @message = Message.new(params[:feedback])
    if @message.valid?
      # TODO send message here
      flash[:notice] = "Message sent! Thank you for contacting us."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end
  
  def comments
    @source = params[:source].to_sym
    @video_id = params[:id]
    if params[:page].blank?
      @page = 1 
    else
      @page = params[:page].to_i
    end

    @comment_count = params[:comment_count].to_i
    @max_results = 5
    @start_index = (@page - 1) * 5 + 1

    if @source == :youtube
      @comments = []

      client = YouTubeIt::Client.new(:username => "ytuservizbuvs", :password =>  "vizbu_ytuser", :dev_key => "AI39si5-1s6CVSSGdBqlMnzN9v_OMBufAMEW-0H4Ke1UG5laQpDCWyWJU5WJlpVHPXSTHyBDHEoFsbBdLfwgHBs7Aic3tjHR0Q")

      yt_comments = client.comments(@video_id, :'max-results' => 5, :'start-index' => @start_index)

      yt_comments.each do |yt_comment|
        comment = {}
        comment[:content] = yt_comment.content
        comment[:author] = { :name => yt_comment.author.name, :url => "http://www.youtube.com/user/#{yt_comment.author.name}"}
        comment[:published_at] = yt_comment.published
        @comments << comment
      end
    else
      not_found
    end
  end

  protected

  def normalize_result(result, type)

    out = {}

    if type == :youtube
      out[:total_videos] = result.total_result_count
      out[:videos] = []

      result.videos.each do |video|
        ov = {}
        ov[:id] = video.unique_id
        ov[:embed_url] = "http://www.youtube.com/embed/#{ video.unique_id }?wmode=opaque&autoplay=1"
        ov[:player_url] = video.player_url
        ov[:thumb_url] = "http://img.youtube.com/vi/#{ video.unique_id }/0.jpg"
        ov[:title] = video.title
        ov[:author_name] = video.author.name
        ov[:author_url] = "http://www.youtube.com/user/#{ video.author.name }"
        ov[:published_at] = video.published_at
        ov[:view_count] = video.view_count
        ov[:has_comments] = video.comment_count
        ov[:comment_count] = video.comment_count
        ov[:duration] = video.duration
        ov[:description] =  video.description
        out[:videos] << ov
      end

    elsif type == :vimeo
      out[:total_videos] = result["videos"]["total"]
      out[:videos] = []

      result["videos"]["video"].each do |video|
        ov = {}
        ov[:id] = video["id"]
        ov[:embed_url] = "http://player.vimeo.com/video/#{ video["id"] }?autoplay=1"
        ov[:player_url] = "http://vimeo.com/#{ video["id"] }"

        ov[:thumb_url] = "/assets/vimeo_default_thumb.jpg"

        thumb_node = video["thumbnails"]["thumbnail"].inject(nil) do |thumb_node, node|
          if !thumb_node || node["width"] != "640"
            thumb_node = node
          end
          thumb_node
        end

        ov[:thumb_url] = thumb_node["_content"] if thumb_node

        ov[:title] = video["title"]
        ov[:author_name] = video["owner"]["display_name"]
        ov[:author_url] = "http://vimeo.com/user#{ video["owner"]["id"] }"
        ov[:published_at] = video["upload_date"]
        ov[:view_count] = video["number_of_plays"]
        ov[:duration] = video["duration"]
        ov[:description] =  video["description"]
        out[:videos] << ov
      end
    elsif type == :soundcloud
      if result.length < 10
        out[:total_videos] = ((@page.to_i - 1 ) * 10) + result.length
      else
        out[:total_videos] = result.length + 50 + @q.hash % 30
      end
      out[:videos] = []

      result.each do |video|
        ov = {}
        ov[:id] = video.id
        ov[:embed_url] = "http://w.soundcloud.com/player/?url=#{ video.uri }&auto_play=false&show_artwork=false&color=0066cc"
        ov[:embed_code] = '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="'+ "http://w.soundcloud.com/player/?url=#{ video.uri }&auto_play=false&show_artwork=false&color=0066cc" +'"></iframe>'
        ov[:height] = 166
        ov[:player_url] = video.permalink_url
        ov[:title] = video.title
        ov[:author_name] = video.user.username
        ov[:author_url] = video.user.permalink_url
        ov[:published_at] = video.created_at
        ov[:view_count] = video.playback_count
        ov[:duration] = video.duration / 1000
        ov[:description] =  video.description
        out[:videos] << ov
      end
    

app/helpers/home_helper.rb
module HomeHelper
  def video_duration(sec)
    sec = sec.to_i
    mins = sec / 60
    sec = sec % 60
    if mins > 60
      hours = mins / 60
      mins = mins % 60
      hours.to_s.rjust(2,'0') + ":" + mins.to_s.rjust(2,'0') + ":" + sec.to_s.rjust(2,'0')
    else
      mins.to_s.rjust(2,'0') + ":" + sec.to_s.rjust(2,'0')
    end
  end
  
  def remove_filters(params)
    out_params = params.dup
    @filters[@source.to_sym].each do |k, v|
      out_params.delete(k.to_sym)
    end
    out_params
  end
  
  def video_embed_code(video, result_type)
    if video[:embed_code]
      video[:embed_code].html_safe
    else
      if result_type == :list
        '<iframe width="560" height="315" src="' + video[:embed_url] + '" frameborder="0" allowfullscreen></iframe>'.html_safe
      else # grid
        '<iframe width="460" height="263" src="' + video[:embed_url] + '" frameborder="0" allowfullscreen></iframe>'.html_safe
      end
    end
  end

end

app/views/home/_comments_list.html.erb
<div class="comments">
  <% @comments.each do |comment| %>
    <%= render "comment", :comment => comment %>
  <% end %>
</div>
<div class="comments_pagination">
  <% if @page > 1 %>
    <%= link_to "Prev", params.merge({ :page => @page - 1 }), :remote => true %>
  <% else %>
    <%= "Prev" %>
  <% end %>
  |
  <% if @comment_count >= @start_index + @max_results %>
    <%= link_to "Next", params.merge({ :page => @page + 1 }), :remote => true %>
  <% else %>
    <%= "Next" %>
  <% end %>
</div>

app/views/home/_full_result.html.erb
<div class="span10">
  <span class="results-for">Search results for <span><%= @q %></span></span>
</div>
<div class="span2">
  <span class="total-results pull-right" style="margin-right:">About <b><%= number_with_delimiter(@result[:total_videos], :delimiter => ',')  %></b> results</span>
</div>
<div class="span12">
  <hr style="margin-top:10px;margin-bottom:5px;" />
    <div id="filter" class="btn-group" style="display:inline-block;float:left;">
      <a class="btn dropdown-toggle " href="#">
        Filter
        <span class="caret"></span>
      </a>
    </div>
    <h3 style="display:inline-block;float:left;padding-left:10px;">
      View : 
      <%= if ( @view == "list" ) then "List" else link_to "List", params.merge({ :view => "list" }), :class => "pjax-enabled" end %> |
      <%= if ( @view == "grid" ) then "Grid" else link_to "Grid", params.merge({ :view => "grid" }), :class => "pjax-enabled" end %>
    </h3>
    <div class="clear"></div>
    <div class="filter-options" style="display:none;">
      <% ( @filters[@source.to_sym] || [] ).each do |k, v| %>
        <div class="span2">
          <h4><%= k.to_s.humanize %> : </h4>
          <% first_filter = true %>
          <% v.each do |filter, condition| %>
            <% if params[k] == filter.to_s || ( params[k].blank? && first_filter ) %>
              <b><%= link_to filter.to_s.humanize, params.merge(k => filter, :page => nil), :class => "pjax-enabled" %></b><br />
            <% else %>
              <%= link_to filter.to_s.humanize, params.merge(k => filter, :page => nil), :class => "pjax-enabled" %><br />
            <% end %>
            <% first_filter = false %>
          <% end %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <hr style="margin-top:5px;margin-bottom:5px;" />
</div>
<% if @result[:videos].empty? %>
  <div class="span12">
    <br />
    <h3>No results found. Try searching something else.</h3>
    <br />
  </div>
<% else %>
  <% @result[:videos].each_with_index do |video, index| %>
    <%= render "result_#{@view}", :video => video, :index => index %>
  <% end %>
<% end %>

<br/>

<%=
 render "pagination", :result => @result
%>
<div class="clear"></div>
<br />
<div class="span12 search-footer">
  <%= link_to "Blog", "http://blog.vizbu.com" %> | <%= link_to "About", "/about" %> | <a href="/privacy">Privacy</a> | <%= link_to "Feedback", "/feedback" %>
</div>
<br /><br />
<br />

app/views/home/_pagination.html.erb
<% max_pages = 10 %>

<% cur_page = (params[:page] || 1).to_i %>
<% next_page = cur_page + 1 %>
<% prev_page = cur_page - 1 %>
<% total_pages = result[:total_videos].to_i / 10 %>

<% padding = 3 %>

<div class="span12 pagination" style="text-align:center;">
  <ul>
    <% if prev_page > 0 %>
      <li><%= link_to "Prev", params.merge( { :page => prev_page } ), :class => "pjax-enabled" %></li>
    <% else %>
      <li class="disabled"><%= link_to "Prev", "#"%></li>
    <% end %>
    <% if cur_page > padding %>
      <% if cur_page - padding < padding then e = ( cur_page - padding - 1) else e = padding end %>
      <% (1..e).each do |p| %>
        <% if cur_page == p %>
          <li class="active"><a href="javascript:return false;"><%= p %></a></li>
        <% else %>
          <li><%= link_to p, params.merge( { :page => p } ), :class => "pjax-enabled" %></li>
        <% end %>
      <% end %>
      <% if cur_page > padding * 2 + 1 %>
        <li class="disabled"><a href="javascript:return false;">...</a></li>
      <% end %>
    <% else %>
      <%  show_extra_to_right = true %>
    <% end %>
    <% if cur_page - padding > 0 then s = ( cur_page - padding) else s = 1 end %>
    <% if cur_page + padding < total_pages %>
      <% if show_extra_to_right %>
        <% e = ( cur_page + padding + padding) %>
      <% else %>
        <% e = ( cur_page + padding) %>
      <% end %>
    <% else %>
      <% e = total_pages %>
    <% end %>   
    <% (s..e).each do |p| %>
      <% if cur_page == p %>
        <li class="active"><a href="javascript:return false;"><%= p %></a></li>
      <% else %>
        <li><%= link_to p, params.merge( { :page => p } ), :class => "pjax-enabled" %></li>
      <% end %>
    <% end %>
    <li class="disabled"><a href="javascript:return false;">...</a></li>
    <% if next_page < total_pages %>
      <li><%= link_to "Next", params.merge( { :page => next_page } ), :class => "pjax-enabled" %></li>
    <% else %>
      <li class="disabled"><%= link_to "Next", "#" %></li>
    <% end %>
  </ul>
</div>

app/views/home/_result.html.erb
<div class="result" style="margin:10px 0 25px 0;">
  <div class="span7 res-thumb" style="width:560px;height:315px;display:inline-block;background-color:Gray;overflow:;">
    <!-- <%= image_tag "http://i.ytimg.com/vi/#{ video.unique_id }/hqdefault.jpg" %> -->
    <iframe width="560" height="315" src="http://www.youtube.com/embed/<%= video.unique_id %>" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="span5 res-data" style="width:360px;height:315px;overflow:hidden;">
    <div class="rel">
      <h3><a href="<%= video.player_url %>" target="_blank"><%= video.title %></a></h3>
      <h5 class="res-stats">
        By <%= link_to video.author.name, "http://www.youtube.com/user/#{ video.author.name }" %> | 1 year ago | <%= number_with_delimiter(video.view_count, :delimiter => ',') %> views
      </h5>
      <p><%= video.description %></p>
      <br />
      <div class="res-more" >
        <span>Show More</span>
      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/home/_result_grid.html.erb
<div class="span6 result-grid" style="margin-bottom:10px;margin-top:10px;height:<%= video[:height] || 264 %>px;">
  <% if video[:thumb_url] %>
    <div class="img-thumb-container" data-embed-code="<%= video_embed_code(video, :grid) %>" >
      <img class="img-thumb" src="<%= video[:thumb_url] %>" ></img>
      <table class="img-player-play-container">
        <tr><td>
          <%= image_tag "player_play.png", :class => "img-player-play" %>
        </td></tr>
      </table>
    </div>
  <% else %>
    <%=raw video_embed_code(video, :grid) %>
  <% end %>
</div>

app/views/home/_result_list.html.erb
<div id="video_<%= video[:id] %>" class="result" style="margin:10px 0 25px 0;">
  <div class="span7 res-thumb" style="width:560px;height:<%= video[:height] || 315 %>px;display:inline-block;background-color:Gray;overflow:;">
    <% if video[:thumb_url] %>
      <div class="img-thumb-container" data-embed-code="<%= video_embed_code(video, :list) %>" >
        <img class="img-thumb" src="<%= video[:thumb_url] %>" ></img>
        <table class="img-player-play-container">
          <tr><td>
            <%= image_tag "player_play.png", :class => "img-player-play" %>
          </td></tr>
        </table>
      </div>
    <% else %>
      <%=raw video_embed_code(video, :list) %>
    <% end %>
  </div>
  <div class="span5 res-data" style="width:360px;height:<%= video[:height] || 315 %>px;overflow:hidden;">
    <div class="rel">
      <h3><a href="<%= video[:player_url] %>" target="_blank"><%= video[:title] %></a></h3>
      <h5 class="res-stats">
        By <%= link_to video[:author_name],video[:author_url], :target => "_blank" %> |
        <%= time_ago_in_words(video[:published_at]) + " ago" %> |
        <%= number_with_delimiter(video[:view_count], :delimiter => ',') %> views |
        <%= video_duration(video[:duration]) %>
      </h5>
      <p class="share_download_links clearfix">
        <%= link_to image_tag("download.png"), "http://offliberty.com/##{video[:player_url]}", :target => "_blank", :class => "download_link", :title => "Download Video" %>
        <%= link_to image_tag("facebook_share.png"), "http://www.facebook.com/sharer.php?u=#{ CGI.escape( video[:player_url] ) }&t=#{ CGI.escape( video[:title] + "via Vizbu" ) }", :target => "_blank", :title => "Share on Facebook" %>
        <%= link_to image_tag("twitter_share.png"), "http://twitter.com/intent/tweet?status=#{ CGI.escape( video[:title] + " " + video[:player_url] + " via @vizbu" ) }", :target => "_blank", :title => "Share on Twitter" %>
      </p>
      <% if video[:has_comments] %>
      <p class="show_comments" ><%= image_tag("comments.png") %>&nbsp;<%= link_to "#{ video[:comment_count] } comments", "#", :data => { :href => comments_path(:source => @source, :id => video[:id], :comment_count => video[:comment_count] ) }, :style => "line-height:20px;" %></p>
      <div class="comments_container" style="display:none;">
        
      </div>
      <% end %>
      <p><%= video[:description] %></p>
      <br />
      <div class="res-more" >
        <span>Show More</span>
      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/home/_result_list_vimeo.html.erb
<div class="result" style="margin:10px 0 25px 0;">
  <div class="span7 res-thumb" style="width:560px;height:315px;display:inline-block;background-color:Gray;overflow:;">
    <iframe width="560" height="315" src="http://player.vimeo.com/video/<%= video["id"] %>" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="span5 res-data" style="width:360px;height:315px;overflow:hidden;">
    <div class="rel">
      <h3><a href="http://vimeo.com/<%= video["id"] %>" target="_blank"><%= video["title"] %></a></h3>
      <h5 class="res-stats">
        By <%= link_to video["owner"]["display_name"], "http://vimeo.com/user#{ video["owner"]["id"] }", :target => "_blank" %> | <%= time_ago_in_words(video["upload_date"]) + " ago" %> | <%= number_with_delimiter(video["number_of_plays"], :delimiter => ',') %> views | <%= video_duration(video["duration"]) %>
      </h5>
      <p><%= video["description"] %></p>
      <br />
      <div class="res-more" >
        <span>Show More</span>
      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/home/_search_form.html.erb
<form action="/search" class="form-horizontal search-form">
  <fieldset>
    <div class="control-group">
      <div class="controls" style="margin:0;">
        <div class="input-append">
          <% if @source %>
            <input type="hidden" id="source" name="source" value="<%= @source %>"></input>
          <% end %>
          <input value="<%= @q %>" name="q" class="span6 search-input" id="searchInput" size="16" type="text" ><button class="btn search-btn" type="submit" >
            <img src="/assets/search.png" style="max-height:12px;max-width:12px;padding-top:6px;"></img>
          </button>
        </div>
      </div>
    </div>
  </fieldset>
</form>

app/views/home/about.html.erb
<div class="row">
  <div class="span12" style="text-align:center;margin-top:40px;margin-bottom:40px;">
    <iframe width="560" height="315" src="http://www.youtube.com/embed/1qg1tfSlZiU" frameborder="0" allowfullscreen></iframe>
    <div class="clear"></div>
    <br />
    
    <table style="margin:0 auto;width:560px;">
      <tr>
        <td style="vertical-align:top;">
          <a href="/"><%= image_tag "logo.png" %></a>
        </td>
        <td style="text-align:left;vertical-align:top;padding-left:10px;">
          <h1>
            is a search engine for videos and music via Youtube, Vimeo and Soundcloud
          </h1>
        </td>
      </tr>
    </table>
  </div>
  <div class="span4">
    <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FVizbudotcom&amp;width=292&amp;height=590&amp;colorscheme=light&amp;show_faces=true&amp;border_color&amp;stream=true&amp;header=true&amp;appId=284529138288915" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:590px;" allowTransparency="true"></iframe>
  </div>
  <div class="span4">
      <!-- Place this tag in the <head> of your document -->
    <script type="text/javascript">
    window.___gcfg = {lang: 'en'};
    (function() 
    {var po = document.createElement("script");
    po.type = "text/javascript"; po.async = true;po.src = "https://apis.google.com/js/plusone.js";
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(po, s);
    })();</script>

    <!-- Place this tag where you want the badge to render -->
    <g:plus href="https://plus.google.com/104414201826448074596" rel="publisher" width="300" height="131" theme="light"></g:plus>
  </div>
  <div class="span4">

    <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
    <script>
    new TWTR.Widget({
      version: 2,
      type: 'profile',
      rpp: 4,
      interval: 30000,
      width: 'auto',
      height: 350,
      theme: {
        shell: {
          background: '#cccccc',
          color: '#000000'
        },
        tweets: {
          background: '#bbbbbb',
          color: '#030303',
          links: '#0c038a'
        }
      },
      features: {
        scrollbar: false,
        loop: false,
        live: false,
        behavior: 'all'
      }
    }).render().setUser('vizbu').start();
    </script>

  </div>
  
  <div class="span12" style="margin-top:40px;margin-bottom:40px;">
    <h1 class="clearfix"><%= image_tag "mail.png", :class => "about-icon" %> <a href="mailto:contact@vizbu.com" class="about-link">contact@vizbu.com</a></h1>
    <h1 class="clearfix"><%= image_tag "facebook.png", :class => "about-icon" %> <a href="https://www.facebook.com/pages/Vizbudotcom/406585199376196" class="about-link">facebook.com/vizbudotcom</a></h1>
    <h1 class="clearfix"><%= image_tag "twitter.png", :class => "about-icon" %> <a href="https://twitter.com/#!/vizbu" class="about-link">twitter.com/vizbu</a></h1>
    <h1 class="clearfix"><%= image_tag "gplus.png", :class => "about-icon" %> <a href="https://plus.google.com/b/104414201826448074596/104414201826448074596/posts" class="about-link">plus.google.com/104414201826448074596/</a></h1>
  </div>

</div>

app/views/home/search.html.erb
<% @title = @q + " - Vizbu" %>

<div class="row">
  <div class="span2">
    <a href="/" class="logo-link"><%= image_tag "logo.png", :class => "small-logo" %></a>
  </div>
  <div class="span10" style="padding:20px 0;">
    <%= render "search_form" %>
  </div>
  <div class="span12" style="">
    <ul id="search-nav" class="nav nav-tabs">
      <% ["youtube", "vimeo", "soundcloud", "dailymotion"].each do |source| %>
        <li class="<%= if source.to_sym == @source then "active" end %>">
          <%= link_to image_tag("#{ source }.png", :class => "search-icon") + " " + content_tag( :span, source.humanize, :class => "source-name" ), remove_filters(params).merge({ :q => @q, :source => source, :page => nil }), :data => { :source => source }, :class => "source-link pjax-enabled" %>
        </li>
      <% end %>
    </ul>
  </div>
  <div id="full-result-container">
    <%= render "full_result" %>
  </div>
</div>

app/views/home/search.js.erb
var $this = $("a[data-source=<%= @source %>]");

$("#search-nav .active").toggleClass("active");
$this.parents("li").toggleClass("active");

var $search_form = $(".search-form");
$search_form.find("input#source").val("<%= @source %>");

var $res_container = $("#full-result-container");
$res_container.html("<div class='loading-results'>Loading results</div>");
$res_container.html("<%= j render "full_result" %>");